name: Build and Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:latest
          provenance: false

      - name: Delete untagged, keep latest
        uses: actions/delete-package-versions@v5
        with:
          package-name: ${{ github.event.repository.name }}
          package-type: container
          delete-only-untagged-versions: true
          min-versions-to-keep: 0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout source code
        uses: actions/checkout@v5

      - name: Deploy to k8s with helm
        uses: WyriHaximus/github-action-helm3@v4
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          overrule_existing_kubeconfig: true
          exec: |
            helm upgrade $(echo "${{ github.event.repository.name }}" | tr -d '.') helm-charts \
              --atomic \
              --debug \
              --history-max 2 \
              --install \
              --set-string image.tag="latest" \
              --set-string "env[0].name=TELEGRAM_SALE_BOT_TOKEN" --set-string "env[0].value=${{ secrets.TELEGRAM_SALE_BOT_TOKEN }}" \
              --set-string "env[1].name=DATABASE_URL" --set-string "env[1].value=${{ secrets.DATABASE_URL }}" \
              --set-string "env[2].name=TELEGRAM_GROUP_ID" --set-string "env[2].value=${{ vars.TELEGRAM_GROUP_ID }}" \
              --set-string "env[3].name=TELEGRAM_GROUP_LINK" --set-string "env[3].value=${{ vars.TELEGRAM_GROUP_LINK }}" \
              --set-string "env[4].name=TELEGRAM_SALE_DAY" --set-string "env[4].value=${{ vars.TELEGRAM_SALE_DAY }}" \
              --set-string podAnnotations.deployedAt="$(TZ='Asia/Jakarta' date +'%Y-%m-%dT%H:%M:%S%z')" \
              --set-string podAnnotations.deployedBy="${{ github.actor }}" \
              --set-string podAnnotations.projectBranch="${{ github.ref_name }}" \
              --set-string podAnnotations.projectCommit="$(echo $GITHUB_SHA | cut -c1-7)" \
              --set-string podAnnotations.projectPath="${{ github.repository }}" \
              --wait
